# -*- coding: utf-8 -*-
"""Matching_Elite_Format

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qV6kXkV8CfM0iehe3nOh0NNgf1-kH0r
"""

import pandas as pd
import numpy as np

df_sample = pd.read_csv('sample_data.csv')

df_sample.head()

df_sample[df_sample['elite'].notnull()]

df_population = pd.read_csv('yelp_academic_dataset_user.csv')

# Keep only 'user_id' and 'elite' columns in the df_population
df_population_filtered = df_population[['user_id', 'elite']]

# Perform a left join between df_sample and df_population_filtered based on 'user_id'
df_merged = pd.merge(df_sample, df_population_filtered, on='user_id', how='left')

df_merged.head()

# Drop the 'elite_x' column since you want to keep the 'elite_y'
df_merged_cleaned = df_merged.drop(columns=['elite_x'])

# Optionally, you can rename 'elite_y' back to 'elite' for clarity
df_merged_cleaned = df_merged_cleaned.rename(columns={'elite_y': 'elite'})

df_merged_cleaned[df_merged_cleaned['elite'].notnull()]

df_merged.to_csv('cleaned_sample_data.csv', index=False)