<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Group_Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Group_Report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Group_Report_files/libs/quarto-html/quarto.js"></script>
<script src="Group_Report_files/libs/quarto-html/popper.min.js"></script>
<script src="Group_Report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Group_Report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Group_Report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Group_Report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Group_Report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Group_Report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Group_Report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Group_Report</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="deliverable-group-12" class="level1">
<h1>Deliverable Group 12</h1>
<p>This report was created for the Data Preparation and Workflow Management course, taught by <strong>Hannes Datta</strong> at the Tilburg School of Economics and Management, as part of the Master’s program in Marketing Analytics. It is a collaboration by Team 12, consisting of:</p>
<ul>
<li><p><strong>Kris Bruurs</strong> - k.bruurs@tilburguniversity.edu</p></li>
<li><p><strong>Ly Ba Tho</strong> - b.t.ly@tilburguniversity.edu</p></li>
<li><p><strong>Jelle de Bie</strong> - j.debie@tilburguniversity.edu</p></li>
<li><p><strong>Zeynep Yavlal</strong> - z.yavlal@tilburguniversity.edu</p></li>
<li><p><strong>Bart van de Mortel</strong> - b.h.l.vdmortel@tilburguniversity.edu</p></li>
</ul>
<section id="do-influential-yelp-users-give-higher-ratings-to-take-out-restaurants-compared-to-non-influential-users-and-how-does-the-factor-of-location-affect-these-ratings" class="level2">
<h2 class="anchored" data-anchor-id="do-influential-yelp-users-give-higher-ratings-to-take-out-restaurants-compared-to-non-influential-users-and-how-does-the-factor-of-location-affect-these-ratings">Do influential Yelp users give higher ratings to take-out restaurants compared to non-influential users, and how does the factor of location affect these ratings?</h2>
<hr>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<p>Since its launch in 2004, Yelp, as one of the largest online review platforms, has played a crucial role in shaping the reputations of businesses, particularly in the food industry. While there is an abundance of research analyzing Yelp reviews (<em>Agarwal, Pelullo, &amp; Merchant 2019; Arthur, Etzioni, &amp; Schwartz, 2019</em>), most studies focus on general patterns of consumer behavior (<em>Fogel, J. and Zachariah, S., 2017</em>), sentiment analysis (<em>Guerreiro &amp; Rita, 2020</em>), or the detection of fake reviews (<em>Lee, Ham, Yang, &amp; Koo, 2018</em>). What these studies largely overlook, however, is the significant role that influential users—those with elite status, numerous followers, or high review counts—play in shaping business ratings (<em>Pranata, I. and Susilo, W., 2016</em>). These users wield disproportionate influence on the platform, and their ratings are often perceived as more credible and trustworthy than those of regular users (<em>Tucker, T., 2011</em>).</p>
<section id="research-motivation" class="level3">
<h3 class="anchored" data-anchor-id="research-motivation">1.1 Research Motivation</h3>
<p>In competitive sectors like the food industry, where reputation can make or break a business, understanding the impact of these influential users is essential, as evidenced in a study conducted by <em>Nakayama and Wan (2018)</em> about one-third of customers rely on online reviews when choosing a restaurant and over half of 18-to-34-year-olds factor reviews into their dining decisions. Moreover, while the food industry on Yelp has been extensively studied (<em>Anderson and Magruder, 2012</em>) because of its tremendous impacts on business outcomes (<em>Luca, 2016</em>), the take-out restaurant niche has received minimal attention. The majority of existing studies on take-out restaurants emphasize negative aspects such as health risks, obesity, and food safety concerns (<em>Jeffery et al., 2006; Baek et al., 2022</em>). These studies tend to focus on the health implications of frequent take-out consumption but fail to address the consumer dynamics on platforms like Yelp, where reviews have the power to influence public perception and business success (<em>Jiménez, et al.&nbsp;2013</em>). Additionally, location, particularly in terms of region, state, and city, plays a pivotal role in how take-out restaurants are rated on Yelp (<em>Tayeen, et al., 2019</em>). Regional preferences can influence the types of cuisines that receive higher ratings, with some regions showing a stronger preference for local or niche food options (<em>Rahimi, et al., 2018</em>). State-level factors such as regulations, food safety laws, and even cultural food trends may also impact how users perceive and rate take-out establishments. Additionally, within cities, neighborhood dynamics like the level of urbanization, socio-economic status, and competition with nearby restaurants can lead to significant variations in ratings (<em>Tayeen, et al., 2021</em>). Influential Yelp users in major metropolitan areas may also drive more reviews and higher visibility for restaurants, skewing ratings compared to those in smaller cities or rural areas. <strong>This gap in the literature calls for a deeper investigation into how influential users interact with take-out restaurants, especially as take-out has become increasingly important in the post-pandemic dining landscape.</strong></p>
<p>The accessibility and usefulness of the output from this study significantly benefit other students and the larger scientific community. By <strong>developing an automated and reproducible workflow using open-source tools like R</strong>, this research provides a template that others can easily adapt for similar analyses. <strong>The study’s findings and the associated code</strong> can be shared on public platforms like GitHub, making them readily available for educational purposes and further research. The workflow includes data extraction, cleaning, transformation, and modeling processes, all documented and scripted to ensure transparency and repeatability. Moreover, the <strong>comprehensive HTML report</strong> serves as a valuable resource that clearly communicates the research methods, analyses, and findings. It can be used as a teaching tool in academic settings, demonstrating how to approach complex data analyses and interpret results within a real-world context.</p>
</section>
<section id="research-question" class="level3">
<h3 class="anchored" data-anchor-id="research-question">1.2 Research Question</h3>
<p>This study aims to address the gap in the dynamics of online reviews, particularly from influential Yelp users, by asking: <strong>Do influential Yelp users give higher ratings to take-out restaurants compared to non-influential users, and how does the factor of location affect these ratings?</strong> This research is critical for several reasons. First, understanding the behavior of influential users could help businesses better manage their online reputations, particularly in a niche market like take-out dining. Second, examining how location—whether at the regional, state, or city level—impacts ratings can provide valuable insights into consumer preferences. Location-specific factors, such as regional food trends, city demographics, and neighborhood characteristics, may influence how users perceive and rate businesses. For take-out restaurants operating in highly competitive environments, especially those without an established offline presence, this research could offer practical strategies for improving ratings and attracting new customers by understanding how geographic context shapes consumer perceptions.</p>
</section>
<section id="conceptual-model" class="level3">
<h3 class="anchored" data-anchor-id="conceptual-model">1.3 Conceptual Model</h3>
<section id="anova" class="level4">
<h4 class="anchored" data-anchor-id="anova">1.3.1 ANOVA</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../3-final_data/ANOVA.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 1.3.1</figcaption>
</figure>
</div>
<p><strong>Independent Variable (Type of Yelp Review): Elite Review, Non-Elite Review</strong></p>
<ul>
<li>This variable represents the categorization of Yelp reviews into two groups: Elite and Non-Elite reviews. The main effect of this variable is to examine how being an elite reviewer or a non-elite reviewer influences the star rating of take-out restaurants. Specifically, we aim to determine whether elite reviewers provide systematically different ratings compared to non-elite reviewers.</li>
</ul>
<p><strong>Quasi-Moderator (State Region): Midwest, Northeast, South, West</strong></p>
<ul>
<li><p>The state region acts as a quasi-moderator in the model. It includes four categories: Midwest, Northeast, South, and West. The main effect of this quasi-moderator is on the star rating of take-out restaurants, allowing us to determine how different regions influence the overall ratings.</p></li>
<li><p>Additionally, interaction effects between the independent variable (type of Yelp review) and the quasi-moderator (state region) will be analyzed. This means we are interested in whether the influence of being an elite or non-elite reviewer on the star ratings of take-out restaurants changes based on the region. For example, elite reviewers in the Midwest might rate take-out restaurants differently compared to elite reviewers in the West.</p></li>
</ul>
<p>To explore these relationships, <strong>ANOVA</strong> will be used as the primary research method. This method is appropriate for comparing the main effects of the independent variable (type of Yelp review) and the quasi-moderator (state region) on the dependent variable (star rating of take-out restaurants). Specifically, ANOVA will allow us to determine whether there are statistically significant differences in star ratings based on the type of reviewer (elite vs.&nbsp;non-elite) and how these effects interact with the state region. The analysis will incorporate columns such as <code>review_id</code>, <code>user_id</code>, <code>business_id</code>, <code>stars_user</code>, <code>review_count_user</code>, <code>fans</code>, <code>state</code>, <code>city</code>, <code>stars_business</code>, <code>review_count_business</code>, <code>is_open</code>, <code>elite_review</code>, <code>division</code>, <code>region</code>, and <code>take_out</code>. By examining these factors, ANOVA will help reveal any meaningful differences in ratings attributable to both reviewer influence and regional variation.</p>
</section>
<section id="regression" class="level4">
<h4 class="anchored" data-anchor-id="regression">1.3.2 Regression</h4>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../3-final_data/Regression.jpeg" class="img-fluid figure-img"></p>
<figcaption>Figure 1.3.2</figcaption>
</figure>
</div>
<p><strong>Independent Variables</strong></p>
<ul>
<li><p><strong>Elite Review:</strong> This variable indicates whether the review was made by an elite Yelp user or a non-elite user. The main effect of this variable is to assess whether there are systematic differences in the <strong>star rating of take-out restaurants</strong> based on the reviewer status. Specifically, we aim to determine if elite reviewers provide higher or lower ratings compared to non-elite reviewers.</p></li>
<li><p><strong>User Review Count:</strong> This variable represents the total number of reviews a user has submitted. The main effect of this variable is to explore how user engagement (as measured by the number of reviews) impacts the <strong>star rating of take-out restaurants</strong>. We aim to understand if prolific reviewers tend to give higher or lower ratings compared to those with fewer reviews.</p></li>
<li><p><strong>Fans:</strong> This variable captures the number of fans a user has, serving as an indicator of their influence within the Yelp community. The main effect of this variable is to determine how a user’s popularity impacts their ratings of take-out restaurants, allowing us to see if more influential users provide systematically different ratings.</p></li>
<li><p><strong>Is_Open:</strong> This variable indicates whether the restaurant is currently open or closed at the time of rating. The main effect of this variable is to investigate whether the operational status of a restaurant influences the <strong>star rating of take-out restaurants</strong>. Specifically, we are interested in whether open restaurants are rated differently compared to those that are closed.</p></li>
</ul>
<p><strong>Dependent Variable</strong></p>
<ul>
<li><strong>Star Rating of Take-Out Restaurants:</strong> The outcome we are interested in predicting is the <strong>star rating</strong> given to take-out restaurants. By analyzing the effects of elite status, user review count, user fans, and restaurant operational status, we aim to gain a deeper understanding of the factors influencing these ratings.</li>
</ul>
<p>To complement the initial <strong>ANOVA</strong> analysis, <strong>regression analysis</strong> will be used to provide a deeper understanding of the relationships between the independent variables and the <strong>star rating of take-out restaurants</strong>. While ANOVA identifies significant differences in star ratings based on reviewer type and region, regression allows us to quantify the unique contributions of multiple predictors, such as <strong>user review count</strong>, <strong>fans</strong>, <strong>is_open</strong>, and <strong>restaurant location</strong>. This approach helps determine the effect size and direction of these influences, providing a comprehensive view of how reviewer characteristics and location impact ratings.</p>
</section>
</section>
<section id="repository-structure-and-documentation" class="level3">
<h3 class="anchored" data-anchor-id="repository-structure-and-documentation">1.4 Repository Structure and Documentation</h3>
<pre class="plaintext"><code>├── README.md
├── makefile
├── updated-project
├── .Rhistory
├── .RData
├── .gitignore
├── 1-docs
│   ├── Group Report.Rproj
│   ├── Group Report.HTML
├── 2-temporary_data
│   ├── cleaned_sample_data
│   ├── sample_data_elite_encoder
│   ├── business_data.csv
│   ├── user_data.csv
│   ├── review_data.csv
│   ├── sample_data.csv
├── 3-final_data
│   ├── takeout_data.csv
├── 4-testing_code
│   ├── download_files_automatically.R
│   ├── label_elite_users.R
│   ├── matching_elite_format.R
│   ├── tar_format_to_json_converter.R
├── 5-external_code
│   ├── json_to_csv_converter.py
├── 6-source_code
│   ├── 0_install_packages.R
│   ├── 1_download_data.R
│   ├── 2_prepare_data.R
│   ├── 3_preprocessing_data.R
│   ├── 4_plot_data.R
│   ├── 5_analyse_data.R
├── 7-plots
├── 8-results
├── 9-shiny_app</code></pre>
</section>
</section>
<section id="data-preparation-analysis" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation-analysis">2. Data Preparation &amp; Analysis</h2>
<section id="data-exploration" class="level3">
<h3 class="anchored" data-anchor-id="data-exploration">2.1 Data Exploration</h3>
<p>Before starting the research, it is advisable to install all the necessary packages that will be used in the study to streamline the workflow.</p>
<ul>
<li><p>here</p></li>
<li><p>rstudioapi</p></li>
<li><p>rstudioapi</p></li>
<li><p>googledrive</p></li>
<li><p>readr</p></li>
<li><p>dplyr</p></li>
<li><p>reticulate</p></li>
<li><p>knitr</p></li>
<li><p>ggcorrplot</p></li>
<li><p>sjPlot</p></li>
<li><p>sjmisc</p></li>
<li><p>gridExtra</p></li>
</ul>
<section id="data-download" class="level4">
<h4 class="anchored" data-anchor-id="data-download">2.1.1 Data Download</h4>
<p>From the Yelp database the business, user, and review data files are downloaded to answer the research question.</p>
<ul>
<li><strong>Yelp Database:</strong> <a href="https://www.yelp.com/dataset/download" class="uri">https://www.yelp.com/dataset/download</a></li>
</ul>
<p>Since the data set is provided in a <code>.tar</code> archive, we need to extract the individual JSON files using R. After extraction, the next step is to convert these JSON files into CSV format using Python scripts. Although we’ve included R and Python code for these processes, we recommend skipping sections <strong>2.1.1.1</strong> and <strong>2.1.1.2</strong>. Instead, proceed directly to <strong>Section 2.1.1.3</strong>, where we introduce code that can automatically download all the necessary files used in this research.</p>
<section id="extract-a-yelp-dataset-in-.tar-format-to-separate-json-files" class="level5">
<h5 class="anchored" data-anchor-id="extract-a-yelp-dataset-in-.tar-format-to-separate-json-files">2.1.1.1 Extract a Yelp dataset in .tar format to separate JSON files</h5>
<pre class="plaintext"><code># Install the archive package
install.packages("archive")

# Load the archive package
library(archive)
library(tidyverse)

# Specify the path to your .rar file
rar_file &lt;- "yelp_dataset.tar"

# Verify if R can see the file
file.exists(rar_file)

# List the contents of the .rar file
contents &lt;- archive::archive(rar_file)
print(contents)

# Specify the extraction directory (make sure it is a directory)
extract_dir &lt;- "extracted_files"

# Create the directory if it doesn't exist
if (!dir.exists(extract_dir)) {
  dir.create(extract_dir)
}

# Extract the files
extracted_files &lt;- archive::archive_extract(rar_file, dir = extract_dir)
print(extracted_files)</code></pre>
</section>
<section id="extract-yelp-datasets-in-.json-format-to-csv-files" class="level5">
<h5 class="anchored" data-anchor-id="extract-yelp-datasets-in-.json-format-to-csv-files">2.1.1.2 Extract Yelp datasets in .JSON format to CSV files</h5>
<pre class="plaintext"><code># -*- coding: utf-8 -*-

import argparse
import csv
import json
import os


def read_and_write_file(json_file, csv_file, column_names):
    with open(json_file, 'r', encoding='utf-8') as f, open(csv_file, 'w', newline='', encoding='utf-8') as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=column_names)
        writer.writeheader()
        for line in f:
            data = json.loads(line)
            writer.writerow(data)
    print(f"CSV file '{csv_file}' has been created successfully.")

def get_superset_of_column_names_from_file(json_file):
    column_names = set()
    with open(json_file, 'r', encoding='utf-8') as f:
        for line in f:
            data = json.loads(line)
            column_names.update(data.keys())
    return list(column_names)


def process_line(line_value):
    row = []
    if isinstance(line_value, str):
        row.append('{0}'.format(line_value))
    elif line_value is not None:
        row.append('{0}'.format(line_value))
    else:
        row.append('')
    return row


if __name__ == '__main__':
    # Convert a yelp dataset file from json to csv.
    print("Starting the conversion process...")

    parser = argparse.ArgumentParser(
        description='Convert Yelp Dataset Challenge data from JSON format to CSV.',
    )

    parser.add_argument(
        'json_file',
        type=str,
        help='The json file to convert.',
    )

    args = parser.parse_args()

    json_file = args.json_file
    csv_file = '{0}.csv'.format(json_file.split('.json')[0])

    # Print current working directory
    print(f"Current working directory: {os.getcwd()}")

    # Print absolute path of the JSON file
    abs_json_file_path = os.path.abspath(json_file)
    print(f"Absolute path of JSON file: {abs_json_file_path}")

    if not os.path.isfile(json_file):
        print(f"Error: The file '{json_file}' does not exist.")
        exit(1)

    print(f"Input JSON file: {json_file}")
    print(f"Output CSV file: {csv_file}")

    column_names = get_superset_of_column_names_from_file(json_file)
    print(f"Column names: {column_names}")

    read_and_write_file(json_file, csv_file, column_names)
    print("Conversion process completed.")</code></pre>
</section>
<section id="download-yelp-data-directly-from-google-drive" class="level5">
<h5 class="anchored" data-anchor-id="download-yelp-data-directly-from-google-drive">2.1.1.3 Download Yelp Data directly from Google Drive</h5>
<p>To streamline the process, we’ve provided an R script that <strong>automatically downloads all the necessary data sets for this study only</strong>. Simply copy and run the code, and it will retrieve all required files directly into your working directory. However, please be aware that for the code to function properly, you’ll need to install both the <strong>googledrive</strong> and <strong>tidyverse</strong> packages. These packages are crucial, especially when dealing with large files, as they ensure smooth data handling and integration within your R environment.</p>
<pre class="plaintext"><code>### Libraries ###
library(tidyverse)
library(here)
library(googledrive)
library(knitr)

### Authentication ###
drive_auth()

### Input ### 

# File ID from Google Drive URLs
business_file_id &lt;- '12o5mGJV8ck_Kqi_x23WF1HbsNGIP70ru'
user_file_id &lt;- '1g-Sy1IMEqrPtPtcc1t2U78iR9Eh8EMtC'
review_file_id &lt;- '1U5rSviYm-EfCxx23EiIAYqNH2JwHp3DT'

# Paths to save the files in the working directory
business_file &lt;- here("2-temporary_data", "business_data.csv")
user_file &lt;- here("2-temporary_data", "user_data.csv")
review_file &lt;- here("2-temporary_data", "review_data.csv")

# Download files using googledrive package
drive_download(as_id(business_file_id), path = business_file, overwrite = TRUE)
drive_download(as_id(user_file_id), path = user_file, overwrite = TRUE)
drive_download(as_id(review_file_id), path = review_file, overwrite = TRUE)

# Load the CSV files into variables
business_data &lt;- read_csv(business_file)
user_data &lt;- read_csv(user_file)
review_data &lt;- read_csv(review_file)</code></pre>
</section>
</section>
<section id="data-inspection" class="level4">
<h4 class="anchored" data-anchor-id="data-inspection">2.1.2 Data Inspection</h4>
<p>The first step after loading the data is to take a look at the different variables that are included in the three different data files.</p>
<section id="business_data" class="level5">
<h5 class="anchored" data-anchor-id="business_data">2.1.2.1 business_data</h5>
<p>The <strong>business_data</strong> set consists of the following variables:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 66%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: center;">Description</th>
<th style="text-align: center;">Data Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">business_id</td>
<td style="text-align: center;">A unique character string for each business</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="even">
<td style="text-align: center;">name</td>
<td style="text-align: center;">The business name</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="odd">
<td style="text-align: center;">address</td>
<td style="text-align: center;">The full address of the business</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="even">
<td style="text-align: center;">city</td>
<td style="text-align: center;">The city name where the business is located</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="odd">
<td style="text-align: center;">state</td>
<td style="text-align: center;">The state name where the business is located</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="even">
<td style="text-align: center;">postal_code</td>
<td style="text-align: center;">The postal code of the business</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="odd">
<td style="text-align: center;">latitude</td>
<td style="text-align: center;">The latitude of the business location</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">longitude</td>
<td style="text-align: center;">The longitude of the business location</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">stars</td>
<td style="text-align: center;">The average star rating rounded to half-stars</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">review_count</td>
<td style="text-align: center;">The number of reviews</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">is_open</td>
<td style="text-align: center;">Variable that shows with 0 (closed) or 1 (open)</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">attributes</td>
<td style="text-align: center;">Business attributes to values</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="odd">
<td style="text-align: center;">categories</td>
<td style="text-align: center;">An array of different business categories</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="even">
<td style="text-align: center;">hours</td>
<td style="text-align: center;">An object of key day-to-value hours</td>
<td style="text-align: center;">Character</td>
</tr>
</tbody>
</table>
</section>
<section id="user_data" class="level5">
<h5 class="anchored" data-anchor-id="user_data">2.1.2.2 user_data</h5>
<p>The <strong>user_data</strong> consists of the following variables:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 47%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: center;">Description</th>
<th style="text-align: center;">Data Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">user_id</td>
<td style="text-align: center;">A unique character string as user identification</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="even">
<td style="text-align: center;">name</td>
<td style="text-align: center;">The user’s first name</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="odd">
<td style="text-align: center;">review_count</td>
<td style="text-align: center;">The number of reviews written by an individual user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">yelping_since</td>
<td style="text-align: center;">Date when user joined Yelp</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="odd">
<td style="text-align: center;">friends</td>
<td style="text-align: center;">An array of the user’s friends as user id’s</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="even">
<td style="text-align: center;">useful</td>
<td style="text-align: center;">Number of ‘useful’ votes send by user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">funny</td>
<td style="text-align: center;">Number of ‘funny’ votes send by user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">cool</td>
<td style="text-align: center;">Number of ‘cool’ votes send by user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">fans</td>
<td style="text-align: center;">The number of fans a user has</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">elite</td>
<td style="text-align: center;">The years the user had an ‘elite’ status on Yelp</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">average_stars</td>
<td style="text-align: center;">Average rating of all reviews</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">compliment_hot</td>
<td style="text-align: center;">Number of ‘hot’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">compliment_more</td>
<td style="text-align: center;">Number of ‘more’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">compliment_profile</td>
<td style="text-align: center;">Number of ‘profile’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">compliment_cute</td>
<td style="text-align: center;">Number of ‘cute’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">compliment_list</td>
<td style="text-align: center;">Number of ‘list’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">compliment_note</td>
<td style="text-align: center;">Number of ‘note’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">compliment_plain</td>
<td style="text-align: center;">Number of ‘plain’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">compliment_cool</td>
<td style="text-align: center;">Number of ‘cool’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">compliment_funny</td>
<td style="text-align: center;">Number of ‘funny’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">compliment_writer</td>
<td style="text-align: center;">Number of ‘writer’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">compliment_photo</td>
<td style="text-align: center;">Number of ‘photo’ compliments received by the user</td>
<td style="text-align: center;">Numeric</td>
</tr>
</tbody>
</table>
</section>
<section id="review_data" class="level5">
<h5 class="anchored" data-anchor-id="review_data">2.1.2.3 review_data</h5>
<p>The <strong>review_data</strong> set consists of the following variables:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 65%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: center;">Description</th>
<th style="text-align: center;">Data Type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">review_id</td>
<td style="text-align: center;">Unique review id</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="even">
<td style="text-align: center;">user_id</td>
<td style="text-align: center;">An unique character string as user id</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="odd">
<td style="text-align: center;">business_id</td>
<td style="text-align: center;">A unique character string for each business</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="even">
<td style="text-align: center;">stars</td>
<td style="text-align: center;">Star rating of the review</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">date</td>
<td style="text-align: center;">Date of review, formatted YYYY-MM-DD</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="even">
<td style="text-align: center;">text</td>
<td style="text-align: center;">The review text</td>
<td style="text-align: center;">Character</td>
</tr>
<tr class="odd">
<td style="text-align: center;">useful</td>
<td style="text-align: center;">The number of ‘useful’ votes received</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="even">
<td style="text-align: center;">funny</td>
<td style="text-align: center;">The number of ‘funny’ votes received</td>
<td style="text-align: center;">Numeric</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Cool</td>
<td style="text-align: center;">The number of ‘cool’ votes received</td>
<td style="text-align: center;">Numeric</td>
</tr>
</tbody>
</table>
</section>
</section>
</section>
<section id="data-processing" class="level3">
<h3 class="anchored" data-anchor-id="data-processing">2.2 <strong>Data Processing</strong></h3>
<p>Due to <strong>limitations such as computational memory constraints and the focus on a manageable data set for in-depth analysis</strong>, we have decided to analyze a <strong>reduced sample of 323,856 observations from the Yelp data set</strong>. This sample size allows us to perform comprehensive statistical analyses while maintaining computational efficiency. <strong>Future research can extend this work by examining the entire population of Yelp reviews</strong>, which could validate our findings on a larger scale and potentially reveal additional insights into the behavior of influential users in the context of take-out restaurants.</p>
<p>Given the <strong>large size</strong> of the three data files and the presence of <strong>many columns not pertinent</strong> to our study, we first <strong>filtered the data sets</strong> to retain only the <strong>necessary variables</strong> before merging them. This step <strong>reduced the data</strong> to a manageable size and ensured that only <strong>relevant information</strong> was included in the subsequent analysis.</p>
<section id="data-inspection-1" class="level4">
<h4 class="anchored" data-anchor-id="data-inspection-1">2.2.1 Data Inspection</h4>
<p>We began by <strong>thoroughly examining</strong> the three large data sets to understand their <strong>structure, content</strong>, and potential issues such as <strong>missing values</strong> or <strong>inconsistencies</strong>.</p>
<p><strong>business data</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 150,346
Columns: 14
$ business_id  &lt;chr&gt; "Pns2l4eNsfO8kk83dixA6A", "mpf3x-BjTdTEA3yCZrAYPw", "tUFr…
$ stars        &lt;dbl&gt; 5.0, 3.0, 3.5, 4.0, 4.5, 2.0, 2.5, 3.5, 3.0, 1.5, 3.5, 4.…
$ name         &lt;chr&gt; "Abby Rappoport, LAC, CMQ", "The UPS Store", "Target", "S…
$ is_open      &lt;dbl&gt; 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, …
$ postal_code  &lt;chr&gt; "93101", "63123", "85711", "19107", "18054", "37015", "63…
$ address      &lt;chr&gt; "1616 Chapala St, Ste 2", "87 Grasso Plaza Shopping Cente…
$ categories   &lt;chr&gt; "Doctors, Traditional Chinese Medicine, Naturopathic/Holi…
$ hours        &lt;chr&gt; NA, "{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', 'Wedne…
$ longitude    &lt;dbl&gt; -119.71120, -90.33570, -110.88045, -75.15556, -75.47166, …
$ city         &lt;chr&gt; "Santa Barbara", "Affton", "Tucson", "Philadelphia", "Gre…
$ latitude     &lt;dbl&gt; 34.42668, 38.55113, 32.22324, 39.95551, 40.33818, 36.2695…
$ review_count &lt;dbl&gt; 7, 15, 22, 80, 13, 6, 13, 5, 19, 10, 6, 10, 28, 10, 100, …
$ attributes   &lt;chr&gt; "{'ByAppointmentOnly': 'True'}", "{'BusinessAcceptsCredit…
$ state        &lt;chr&gt; "CA", "MO", "AZ", "PA", "PA", "TN", "MO", "FL", "MO", "TN…</code></pre>
</div>
</div>
<p><strong>user data</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,987,897
Columns: 22
$ friends            &lt;chr&gt; "NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA, Ej…
$ funny              &lt;dbl&gt; 1259, 13066, 1010, 330, 15, 9940, 1, 102, 40, 20, 0…
$ elite              &lt;dbl&gt; 2.007000e+03, 2.009201e+51, 2.009201e+19, 2.009201e…
$ fans               &lt;dbl&gt; 267, 3138, 52, 28, 1, 1357, 1, 23, 7, 4, 1, 31, 4, …
$ useful             &lt;dbl&gt; 7217, 43091, 2086, 512, 29, 14953, 6, 399, 109, 154…
$ average_stars      &lt;dbl&gt; 3.91, 3.74, 3.32, 4.27, 3.54, 3.85, 2.75, 3.73, 4.0…
$ compliment_list    &lt;dbl&gt; 18, 251, 3, 2, 0, 147, 0, 0, 0, 0, 0, 5, 0, 0, 0, 3…
$ compliment_writer  &lt;dbl&gt; 239, 1521, 35, 10, 0, 815, 0, 5, 3, 0, 0, 24, 1, 0,…
$ compliment_photos  &lt;dbl&gt; 180, 1946, 18, 9, 0, 323, 0, 0, 1, 0, 0, 7, 0, 0, 0…
$ compliment_hot     &lt;dbl&gt; 250, 1145, 89, 24, 1, 1713, 0, 4, 2, 0, 0, 23, 4, 0…
$ user_id            &lt;chr&gt; "qVc8ODYU5SZjKXVBgXdI7w", "j14WgRoU_-2ZE1aw1dXrJg",…
$ compliment_profile &lt;dbl&gt; 55, 184, 10, 1, 0, 191, 0, 2, 0, 0, 0, 1, 0, 0, 0, …
$ compliment_more    &lt;dbl&gt; 65, 264, 13, 4, 1, 163, 0, 7, 0, 0, 0, 9, 0, 0, 0, …
$ compliment_note    &lt;dbl&gt; 232, 1847, 66, 12, 1, 1212, 0, 8, 3, 1, 0, 31, 1, 0…
$ yelping_since      &lt;dttm&gt; 2007-01-25 16:47:26, 2009-01-25 04:35:42, 2008-07-…
$ compliment_plain   &lt;dbl&gt; 844, 7054, 96, 16, 1, 5696, 1, 6, 4, 6, 0, 41, 5, 0…
$ compliment_cute    &lt;dbl&gt; 56, 157, 17, 6, 0, 361, 0, 0, 3, 0, 0, 3, 0, 0, 0, …
$ cool               &lt;dbl&gt; 5994, 27281, 1003, 299, 7, 11211, 0, 143, 46, 23, 1…
$ review_count       &lt;dbl&gt; 585, 4333, 665, 224, 79, 1221, 12, 358, 40, 109, 4,…
$ compliment_funny   &lt;dbl&gt; 467, 3131, 119, 26, 0, 2543, 0, 12, 5, 3, 0, 36, 0,…
$ compliment_cool    &lt;dbl&gt; 467, 3131, 119, 26, 0, 2543, 0, 12, 5, 3, 0, 36, 0,…
$ name               &lt;chr&gt; "Walker", "Daniel", "Steph", "Gwen", "Karen", "Jane…</code></pre>
</div>
</div>
<p><strong>review data</strong></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 500,000
Columns: 9
$ funny       &lt;dbl&gt; 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 2, 0, 0…
$ review_id   &lt;chr&gt; "5IkRlhzFJaBq9mtXAdPYTw", "YGMq3Ui5S6V8nr7qx8aScQ", "BfTIw…
$ stars       &lt;dbl&gt; 4, 1, 2, 3, 5, 4, 4, 3, 5, 1, 1, 4, 1, 4, 3, 4, 5, 1, 5, 3…
$ business_id &lt;chr&gt; "CxXYiJBkq9kqsgtdagqVgw", "eRdMVvBObDLkZ5ykz1irkg", "D44IB…
$ useful      &lt;dbl&gt; 1, 1, 4, 1, 8, 0, 2, 0, 0, 2, 7, 0, 0, 2, 0, 0, 0, 6, 0, 0…
$ text        &lt;chr&gt; "Bacio is a great little neighborhood restaurant.  My husb…
$ user_id     &lt;chr&gt; "vfKLxkxyr6-81WgeSBiHMg", "Zi4EOZ-BQk-6sK3Qd-Ucnw", "S_w84…
$ cool        &lt;dbl&gt; 1, 0, 1, 0, 5, 0, 2, 0, 0, 0, 5, 0, 0, 1, 1, 0, 0, 0, 0, 0…
$ date        &lt;dttm&gt; 2010-12-24 19:01:48, 2020-11-23 13:42:32, 2010-09-20 14:2…</code></pre>
</div>
</div>
</section>
<section id="variable-selection" class="level4">
<h4 class="anchored" data-anchor-id="variable-selection">2.2.2 Variable Selection</h4>
<p>To <strong>focus on relevant information</strong> and <strong>reduce computational complexity</strong>, we <strong>selected only the variables necessary</strong> for our study. This involved <strong>identifying and retaining columns</strong> that contribute directly to our <strong>research objectives</strong> while <strong>discarding irrelevant or redundant data</strong>.</p>
<p>The different variables are evaluated and a selection of variables is chosen to keep in the data set to help answer the research question.</p>
<p>These variables in the <strong>business data</strong> <strong>set</strong> include:</p>
<ul>
<li><p>business_id</p></li>
<li><p>city</p></li>
<li><p>state</p></li>
<li><p>stars</p></li>
<li><p>review_count</p></li>
<li><p>is_open</p></li>
<li><p>attributes</p></li>
</ul>
<p>These variables in the <strong>user data set</strong> include:</p>
<ul>
<li><p>user_id</p></li>
<li><p>review_count</p></li>
<li><p>fans</p></li>
<li><p>elite</p></li>
</ul>
<p>These variables in the <strong>review data set</strong> are:</p>
<ul>
<li><p>user_id</p></li>
<li><p>business_id</p></li>
<li><p>review_id</p></li>
<li><p>stars</p></li>
</ul>
</section>
<section id="data-merging" class="level4">
<h4 class="anchored" data-anchor-id="data-merging">2.2.3 Data Merging</h4>
<p>After <strong>selecting the necessary columns</strong> in each individual data set, we <strong>merged them based on common keys</strong>. This integration allowed us to have a <strong>comprehensive view of the data</strong>, combining <strong>user information, business details, and review content</strong> into a single data set.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>First Few Rows of Selected Sample Data</caption>
<colgroup>
<col style="width: 5%">
<col style="width: 3%">
<col style="width: 1%">
<col style="width: 1%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 1%">
<col style="width: 4%">
<col style="width: 1%">
<col style="width: 3%">
<col style="width: 1%">
<col style="width: 3%">
<col style="width: 1%">
<col style="width: 59%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">user_id</th>
<th style="text-align: right;">review_count.x</th>
<th style="text-align: right;">fans</th>
<th style="text-align: right;">elite</th>
<th style="text-align: left;">review_id</th>
<th style="text-align: left;">business_id</th>
<th style="text-align: right;">stars.x</th>
<th style="text-align: left;">name</th>
<th style="text-align: left;">state</th>
<th style="text-align: left;">city</th>
<th style="text-align: right;">stars.y</th>
<th style="text-align: right;">review_count.y</th>
<th style="text-align: right;">is_open</th>
<th style="text-align: left;">attributes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">q3tdPA76s36oc8v5F8XB0Q</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">NcsMgXGvsCthFvbnbXQ8Sg</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">T6duld__CyiOa4C258gyww</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">2RsuWdxR7OF_b4kCLRwyHA</td>
<td style="text-align: left;">iuKzxuAgf2ttgOyxyLHEMQ</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Philly Dance Fitness</td>
<td style="text-align: left;">PA</td>
<td style="text-align: left;">Philadelphia</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">{‘ByAppointmentOnly’: ‘False’, ‘BusinessAcceptsCreditCards’: ‘True’, ‘BusinessParking’: “{‘garage’: False, ‘street’: True, ‘validated’: False, ‘lot’: False, ‘valet’: False}”, ‘GoodForKids’: ‘False’, ‘WheelchairAccessible’: ‘False’, ‘BikeParking’: ‘True’}</td>
</tr>
<tr class="even">
<td style="text-align: left;">HWKrzYmRIWsNkn6-o_7OXg</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="odd">
<td style="text-align: left;">l_Wx6_nbDvtFgRPijyggAQ</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
<tr class="even">
<td style="text-align: left;">0jZFs6uPO–VVVBf6XbRxw</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: left;">NA</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="data-transformation" class="level4">
<h4 class="anchored" data-anchor-id="data-transformation">2.2.4 Data Transformation</h4>
<p>To <strong>prepare the new data set</strong> for subsequent use, we <strong>transformed the data</strong> by <strong>renaming the columns</strong> to have <strong>meaningful and easily traceable names</strong>. For example, stars.x -&gt; stars_user, stars.y -&gt; stars_business.</p>
<p>Next, we encoded the <code>elite</code> column using the <strong>dummy encoding method</strong> to convert it into a <strong>binary variable</strong>. This transformation allowed us to represent the ‘elite’ status numerically, assigning a value of <strong>1</strong> to <strong>elite users</strong> and <strong>0</strong> to <strong>non-elite users</strong>. By doing so, we made the <code>elite</code> variable suitable for statistical analysis and modeling techniques that require numerical input. This encoding is essential for including categorical variables in regression models, correlation analyses, and other quantitative methods. It enabled us to examine the <strong>impact of a user’s elite status</strong> on various outcomes, such as their <strong>rating behavior</strong> or <strong>influence within the platform</strong>. <strong>Converting categorical data into a numerical format</strong> ensures that the algorithms can <strong>process the information effectively</strong>, leading to <strong>more accurate and meaningful insights</strong> in our analysis.</p>
<p>To thoroughly extract meaningful insights from the data set and address our research question comprehensively, we enhanced the data set by creating additional columns, specifically <code>state_divisions</code> and <code>state_regions</code>. The purpose of these new columns is to <strong>categorize the data more effectively</strong> based on <strong>geographic attributes</strong>, enabling us to conduct a <strong>more granular analysis</strong>. By <strong>segmenting the data set</strong> into distinct <strong>state divisions and regions</strong>, we can <strong>capture the influence of geographical variations</strong> on user ratings, thus <strong>diversifying and deepening our analysis</strong>. This approach allows us to <strong>identify patterns and trends</strong> that might differ across various locations, providing a <strong>more nuanced understanding</strong> of how influential users rate take-out restaurants.</p>
<p>In the subsequent step, we conduct a <strong>thorough examination</strong> to determine whether our data set contains any <strong>missing values</strong>, represented as <strong>‘NA’</strong>. <strong>Identifying and addressing these ‘NA’ values</strong> is crucial to <strong>maintaining the quality and integrity</strong> of our analysis. Once detected, we proceed to <strong>remove these missing values</strong> to prevent them from <strong>skewing our results</strong> or <strong>introducing biases</strong> in the analysis. By <strong>eliminating incomplete data</strong>, we ensure that our data set remains <strong>consistent</strong>, allowing us to <strong>derive accurate insights</strong> and <strong>maintain the robustness</strong> of our statistical models.</p>
<p>To facilitate the analysis of take-out versus non-take-out restaurants, we create a new variable called <code>take_out</code>. This variable will serve as an indicator, where a value of <code>1</code> represents take-out restaurants, and a value of <code>0</code> represents non-take-out establishments. This binary classification allows us to clearly differentiate between the two categories and conduct targeted analyses specific to take-out services.</p>
<p>After defining this variable, we filter our data set to include only those rows where <code>take_out</code> is equal to <code>1</code>. By <strong>focusing exclusively on take-out restaurants</strong>, we can <strong>delve deeper</strong> into the <strong>behaviors, characteristics, and ratings</strong> associated specifically with this subset of businesses, thereby providing <strong>more relevant insights</strong> in relation to our research question. This <strong>filtering step</strong> ensures that our analysis remains <strong>focused on the intended subject</strong>, <strong>eliminating any noise</strong> that non-take-out restaurants might introduce.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>First Few Rows of Selected Takeout Data</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 4%">
<col style="width: 7%">
<col style="width: 1%">
<col style="width: 13%">
<col style="width: 2%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 7%">
<col style="width: 3%">
<col style="width: 3%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">review_id</th>
<th style="text-align: left;">user_id</th>
<th style="text-align: left;">business_id</th>
<th style="text-align: right;">stars_user</th>
<th style="text-align: right;">review_count_user</th>
<th style="text-align: right;">fans</th>
<th style="text-align: left;">username</th>
<th style="text-align: left;">state</th>
<th style="text-align: left;">city</th>
<th style="text-align: right;">stars_business</th>
<th style="text-align: right;">review_count_business</th>
<th style="text-align: right;">is_open</th>
<th style="text-align: right;">elite_review</th>
<th style="text-align: left;">division</th>
<th style="text-align: left;">region</th>
<th style="text-align: right;">take_out</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">5IkRlhzFJaBq9mtXAdPYTw</td>
<td style="text-align: left;">vfKLxkxyr6-81WgeSBiHMg</td>
<td style="text-align: left;">CxXYiJBkq9kqsgtdagqVgw</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">35</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Bacio</td>
<td style="text-align: left;">PA</td>
<td style="text-align: left;">Philadelphia</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">183</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Middle Atlantic</td>
<td style="text-align: left;">Northeast</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">BfTIwT_T6BocpoIh-OPOKA</td>
<td style="text-align: left;">S_w84GR_6oie5WrWICeggg</td>
<td style="text-align: left;">D44IBRDtEScaWELey5IfCA</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">May’s Counter Chicken And Waffles</td>
<td style="text-align: left;">AZ</td>
<td style="text-align: left;">Tucson</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">408</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Mountain</td>
<td style="text-align: left;">West</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">p6rpQJaUVS56I9YIn2lRpQ</td>
<td style="text-align: left;">VVvvI19zeT6ZQFMRgY4gMg</td>
<td style="text-align: left;">uGo0TCVNOcDQxMArUU0Jrw</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">177</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Cajun Kitchen Cafe</td>
<td style="text-align: left;">CA</td>
<td style="text-align: left;">Goleta</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">561</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Pacific</td>
<td style="text-align: left;">West</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">7I-NtFInecg9oCrSQm9T1g</td>
<td style="text-align: left;">ex17cuzocQMKOca_CQb0jA</td>
<td style="text-align: left;">WnVNjr9zVEpK85T7dbAfEg</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Santa Cruz Sushi</td>
<td style="text-align: left;">NV</td>
<td style="text-align: left;">Reno</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Mountain</td>
<td style="text-align: left;">West</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">FrGOp2DqC44GeN44aycGLw</td>
<td style="text-align: left;">wiu8ACeBCxcn6JLnLSVokg</td>
<td style="text-align: left;">dzeBiAu0VAaVBbMwcV9GFw</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Rooster - South Grand</td>
<td style="text-align: left;">MO</td>
<td style="text-align: left;">Saint Louis</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">748</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">West North Central</td>
<td style="text-align: left;">Midwest</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">ZWWKh5pTe5twqar_zbbSGw</td>
<td style="text-align: left;">dCehRsK_TxjZ3hHfwkVG2A</td>
<td style="text-align: left;">PVVFos1LDfD7iETY0w4vaA</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">59</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Su Xing House</td>
<td style="text-align: left;">PA</td>
<td style="text-align: left;">Philadelphia</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">417</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: left;">Middle Atlantic</td>
<td style="text-align: left;">Northeast</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="analysis-and-deployment" class="level3">
<h3 class="anchored" data-anchor-id="analysis-and-deployment">2.3 <strong>Analysis and Deployment</strong></h3>
<section id="exploratory-data-analysis" class="level4">
<h4 class="anchored" data-anchor-id="exploratory-data-analysis">2.3.1 Exploratory Data Analysis</h4>
<p>In this stage, we use various <strong>visualization techniques</strong> such as <strong>bar charts, scatter plots, box plots, and histograms</strong> to <strong>explore relationships</strong> between variables, <strong>uncover patterns</strong>, and <strong>highlight trends</strong> within the data set. Effective data visualization enables us to <strong>quickly identify outliers, distributions, and correlations</strong> that might not be apparent from numerical summaries alone.</p>
<p><strong>Plot 1:</strong> <strong>Distribution of User Ratings by Elite Status</strong></p>
<p>The “<strong>Distribution of User Ratings by Elite Status</strong>” plot illustrates how <strong>ratings differ between elite and non-elite users</strong>. By <strong>comparing the distribution</strong> of ratings across these groups, we aim to determine whether <strong>elite users</strong>, who are often more <strong>experienced or influential</strong>, tend to <strong>rate businesses differently</strong> compared to regular users. This visualization helps us <strong>identify any biases or tendencies</strong> in rating behavior based on <strong>elite status</strong>, providing <strong>insights</strong> into how influential users perceive take-out restaurants compared to non-influential ones.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../7-plots/distribution_user_ratings_by_elite_review.png" class="img-fluid figure-img"></p>
<figcaption>Figure 1</figcaption>
</figure>
</div>
<p><strong>Plot 2: Distribution of User Ratings for Take-Out Restaurants by Elite Status</strong></p>
<p>The “<strong>Distribution of User Ratings for Take-Out Restaurants by Elite Status</strong>” plot shows how <strong>ratings vary between elite and non-elite users</strong> specifically for take-out restaurants. This comparison allows us to <strong>assess whether elite users</strong>, who may have <strong>higher expectations or more experience</strong>, <strong>rate take-out establishments differently</strong> than non-elite users. By visualizing these distributions, we can better understand any <strong>distinctions in rating behavior</strong> linked to <strong>elite status</strong> within the context of <strong>take-out dining</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../7-plots/distribution_ratings_takeout_by_elite_review.png" class="img-fluid figure-img"></p>
<figcaption>Figure 2</figcaption>
</figure>
</div>
<p><strong>Plot 3: Average User Rating by Region and Elite Status</strong></p>
<p>The “<strong>Average User Rating by Region and Elite Status</strong>” plot displays the <strong>average ratings given by users</strong>, segmented by both <strong>region and elite status</strong>. This plot helps us explore whether <strong>elite and non-elite users rate take-out restaurants differently</strong> across various regions. By analyzing these averages, we can <strong>identify regional patterns</strong> in <strong>user satisfaction</strong> and understand if <strong>elite users consistently rate higher or lower</strong> compared to non-elite users in different geographic areas, revealing potential <strong>regional biases or differences in rating behavior</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../7-plots/user_ratings_by_region_elite_review.png" class="img-fluid figure-img"></p>
<figcaption>Figure 3</figcaption>
</figure>
</div>
<p><strong>Plot 4: Distribution of Review Count by Business Open Status</strong></p>
<p>The “<strong>Distribution of Review Count by Business Open Status</strong>” plot shows how the <strong>number of reviews</strong> is distributed between <strong>businesses that are currently open</strong> versus those that are <strong>closed</strong>. This comparison allows us to <strong>examine whether businesses that are still operating</strong> tend to have more or fewer reviews compared to those that have closed, providing <strong>insights into customer engagement</strong> and potential <strong>correlations between review volume and business success</strong> or longevity.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../7-plots/distribution_review_count_business_by_is_open.png" class="img-fluid figure-img"></p>
<figcaption>Figure 4</figcaption>
</figure>
</div>
<p><strong>Plot 5: Average User Rating of Businesses with Review Count &gt; 1000 by Region and Elite Status</strong></p>
<p>The “<strong>Average User Rating of Businesses with Review Count &gt; 1000 by Region and Elite Status</strong>” plot displays the <strong>average ratings</strong> for businesses that have accumulated <strong>more than 1,000 reviews</strong>, segmented by <strong>region and user elite status</strong>. This plot aims to assess whether <strong>businesses with high engagement</strong> are rated differently by <strong>elite versus non-elite users</strong> across different regions, helping us <strong>identify potential regional variations</strong> in <strong>user satisfaction</strong> for <strong>highly popular establishments</strong> and whether <strong>elite users consistently provide higher or lower ratings</strong> compared to non-elite users.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../7-plots/avg_rating_gt_1000_by_region.png" class="img-fluid figure-img"></p>
<figcaption>Figure 5</figcaption>
</figure>
</div>
<p><strong>Plot 6: Average User Rating of Businesses with Review Count &gt; 1000 by Open Status and Elite Status</strong></p>
<p>The “<strong>Average User Rating of Businesses with Review Count &gt; 1000 by Open Status and Elite Status</strong>” plot shows the <strong>average ratings</strong> for businesses that have received <strong>over 1,000 reviews</strong>, segmented by whether the <strong>business is currently open or closed</strong>, and by <strong>user elite status</strong>. This visualization helps us <strong>determine if there is a difference</strong> in how <strong>elite and non-elite users rate highly-reviewed businesses</strong> based on their <strong>open status</strong>, providing <strong>insights</strong> into whether ratings might reflect a <strong>business’s success or its likelihood of remaining open</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../7-plots/avg_rating_gt_1000_by_is_open.png" class="img-fluid figure-img"></p>
<figcaption>Figure 6</figcaption>
</figure>
</div>
<p><strong>Plot 7: Average User Rating of Businesses with Review Count &lt; 1000 by Region and Elite Status</strong></p>
<p>The “<strong>Average User Rating of Businesses with Review Count &lt; 1000 by Region and Elite Status</strong>” plot displays the <strong>average ratings</strong> for businesses with <strong>fewer than 1,000 reviews</strong>, segmented by <strong>region and user elite status</strong>. This plot helps us understand how <strong>elite and non-elite users rate less popular businesses</strong> across different regions, revealing potential <strong>differences in rating behavior</strong> based on <strong>elite status and geographic location</strong>, as well as <strong>regional factors</strong> that might influence <strong>user satisfaction</strong> for businesses with <strong>lower engagement</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../7-plots/avg_rating_lt_1000_by_region.png" class="img-fluid figure-img"></p>
<figcaption>Figure 7</figcaption>
</figure>
</div>
<p><strong>Plot 8: Average User Rating of Businesses with Review Count &lt; 1000 by Open Status and Elite Status</strong></p>
<p>The “<strong>Average User Rating of Businesses with Review Count &lt; 1000 by Open Status and Elite Status</strong>” plot shows the <strong>average ratings</strong> for businesses with <strong>fewer than 1,000 reviews</strong>, segmented by whether the <strong>business is open or closed</strong>, and by <strong>user elite status</strong>. This plot helps us <strong>assess whether elite and non-elite users rate less popular businesses differently</strong> depending on whether they are <strong>still operating</strong>, providing <strong>insights</strong> into how <strong>user ratings</strong> may relate to the <strong>success or closure</strong> of businesses with <strong>lower engagement</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../7-plots/avg_rating_lt_1000_by_is_open.png" class="img-fluid figure-img"></p>
<figcaption>Figure 8</figcaption>
</figure>
</div>
<p><strong>Plot 9: Relationship Between Number of Fans and User Rating by Region and Open Status</strong></p>
<p>The “<strong>Relationship Between Number of Fans and User Rating by Region and Open Status</strong>” plot visualizes how the <strong>number of fans</strong> a user has <strong>correlates with their ratings</strong> of businesses, segmented by both <strong>regions</strong> and whether the <strong>business is open or closed</strong>. This plot helps us understand if <strong>users with more fans</strong>, who may be more <strong>influential</strong>, tend to give <strong>different ratings</strong> based on <strong>regional factors</strong> and the <strong>current status</strong> of the business, providing <strong>insights</strong> into whether <strong>user popularity affects rating behavior</strong> and how this varies by <strong>location and business longevity</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../7-plots/relationship_fans_user_rating_faceted_by_region.png" class="img-fluid figure-img"></p>
<figcaption>Figure 9</figcaption>
</figure>
</div>
<p>Based on our exploratory analysis, we identified several key insights into how user ratings vary based on elite status, geographic region, business status, and user influence.</p>
<ul>
<li><p><strong>Distribution of User Ratings by Elite Status</strong>: Non-elite reviewers are more likely to give higher ratings compared to elite reviewers, with significantly more 5-star ratings coming from non-elite users. This suggests a more generous evaluation pattern among non-elite reviewers.</p></li>
<li><p><strong>Average Rating by Elite Status</strong>: Both elite and non-elite reviewers give an average rating of 4.0 stars to take-out establishments, indicating similar overall attitudes towards these businesses.</p></li>
<li><p><strong>Distribution of User Ratings by Region and Elite Status</strong>: Geographic differences affect rating behavior, with elite users providing higher ratings, especially in the Midwest (4.0 stars). Non-elite reviewers tend to give similar average ratings across all regions (3.7 stars).</p></li>
<li><p><strong>Impact of Business Open Status and Review Counts</strong>: Open businesses generally have more reviews than closed ones, suggesting that higher engagement may be linked to business longevity.</p></li>
<li><p><strong>High Review Counts (&gt;1000)</strong>:</p>
<ul>
<li><p>Non-elite reviewers give consistently higher average ratings than elite reviewers, except in the South.</p></li>
<li><p>Open businesses receive higher ratings from both elite and non-elite users compared to closed businesses. For closed businesses, elite users give much lower ratings (3.1 stars) compared to non-elite users (4.2 stars), implying that elite reviews may influence business survival.</p></li>
</ul></li>
<li><p><strong>Low Review Counts (&lt;1000)</strong>:</p>
<ul>
<li><p>Elite users tend to rate businesses with fewer reviews more favorably than non-elite users across all regions. This may indicate elite reviewers having better experiences, meeting higher expectations, or possible sponsorship.</p></li>
<li><p>The difference in average ratings between open and closed businesses is minimal for businesses with low review counts, regardless of elite status.</p></li>
</ul></li>
<li><p><strong>Relationship Between Number of Fans and User Rating</strong>: There is a high correlation between the number of fans a user has and the ratings they give, particularly in the Midwest and West regions. This suggests that more popular users may be more inclined to rate businesses favorably, which could reflect their influence on user engagement.</p></li>
</ul>
</section>
<section id="statistical-data-analysis" class="level4">
<h4 class="anchored" data-anchor-id="statistical-data-analysis">2.3.2 Statistical Data Analysis</h4>
</section>
<section id="factorial-anova" class="level4">
<h4 class="anchored" data-anchor-id="factorial-anova">Factorial Anova</h4>
<p>A Factorial ANOVA was conducted to compare the main effects of <strong>Review Type</strong> and <strong>State Regions</strong> and the interaction between <strong>Review Type</strong> and <strong>State Regions</strong> on <strong>User Star Ratings of Takeout Restaurants</strong>. <strong>Review Type</strong> included two levels (Elite Review, Non-Elite Review) and <strong>State Regions</strong> types included four levels (Midwest, Northeast, South, West). All effects were statistically significant at the .05 significance level.</p>
<p>The main effect for <strong>Review Type</strong> was significant, <strong>F</strong>(1, 323848) = 1419,98, <strong>p</strong> &lt; .001, with a small effect size, η2 = 0.004, 95% CI [0.00, 1.00], indicating a significant difference between the two review types. Specifically, the mean rating for non-elite reviewers (<strong>M</strong> = 3.74, <strong>SD</strong> = 1.49) was lower than that for elite reviewers (<strong>M</strong> = 3.95, <strong>SD</strong> = 1.05), suggesting that elite reviewers tend to give higher ratings.</p>
<p>The main effect of <strong>State Region</strong> was significant, <strong>F</strong>(3, 323848) = 71.79, <strong>p</strong> &lt; .001, with a smaller effect size, η2 = 0.0007, 95% CI [0.00, 1.00], indicating that there were significant differences in mean ratings across regions. Specifically, the mean ratings were as follows: Midwest (<strong>M</strong> = 3.81, <strong>SD</strong> = 1.38), Northeast (<strong>M</strong> = 3.73, <strong>SD</strong> = 1.38), South (<strong>M</strong> = 3.82, <strong>SD</strong> = 1.39), and West (<strong>M</strong> = 3.79, <strong>SD</strong> = 1.43).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_Report_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_Report_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Pairwise comparisons with Bonferroni adjustment revealed that the Northeast had significantly lower mean ratings compared to the Midwest (<strong>p</strong> &lt; .001), South (<strong>p</strong> &lt; .001), and West (<strong>p</strong> &lt; .001). The South had significantly higher mean ratings compared to the Northeast (<strong>p</strong> &lt; .001) and the West (<strong>p</strong> &lt; .001), but not significantly different from the Midwest (<strong>p</strong> = .146). The Midwest and West were not significantly different (<strong>p</strong> = .062).</p>
<p>The interaction effect of <strong>Review Type</strong> <strong>x State Region</strong> was also significant, <strong>F</strong>(3, 323848) - 12.29, <strong>p</strong> &lt; .001, with a very small effect size, η2 = 0.0001, 95% CI [0.00, 1.00].</p>
<p>These results indicate that both <strong>Review Type</strong> and <strong>State Region</strong> had statistically significant, though small, effects on rating, with the Northeast region generally showing the lowest ratings, and elite reviewer giving slightly higher ratings overall. The interaction between <strong>Review Type</strong> and <strong>State Region</strong> had a minimal influence on the results.</p>
</section>
</section>
<section id="regression-1" class="level3">
<h3 class="anchored" data-anchor-id="regression-1">Regression</h3>
<p>A multiple linear regression was calculated to predict <strong>User Ratings (stars_user)</strong> based on <strong>Elite Review Status (elite_review)</strong>, <strong>Review Count (review_count_user)</strong>, <strong>Number of Fans (fans)</strong>, and <strong>whether the Business is Open (is_open)</strong>. A significant regression equation was found, <strong>F(4, 323851) = 603.4</strong>, p &lt; .001, with an R² of <strong>.007</strong>. This indicates that approximately <strong>0.74%</strong> of the variance in user ratings is explained by the variables included in the model, suggesting that other factors not included in the model may also contribute significantly to predicting user ratings.</p>
<p>Participants’ predicted user rating is equal to <strong>3.59 + 0.2315</strong> (elite_review) <strong>- 0.0000868</strong> (review_count_user) <strong>+ 0.0001787</strong> (fans) <strong>+ 0.1824</strong> (is_open), where:</p>
<ul>
<li><p><strong>elite_review</strong> is coded as 1 if the user has elite status and 0 otherwise,</p></li>
<li><p><strong>is_open</strong> is coded as 1 if the business is open and 0 if it is closed.</p></li>
</ul>
<p>User ratings increased by <strong>0.2315 stars</strong> for users with elite status and by <strong>0.1824 stars</strong> for businesses that are open. Both <strong>elite_review</strong> and <strong>is_open</strong> were significant predictors of user ratings (p &lt; .001). While <strong>review_count_user</strong> had a small negative effect (with user ratings decreasing by <strong>0.0000868 stars</strong> for each additional review written), and <strong>fans</strong> had a small positive effect (with user ratings increasing by <strong>0.0001787 stars</strong> for each additional fan), their contributions to the model were also statistically significant.</p>
<p>In conclusion, while elite status and the open status of a business have a noticeable positive impact on user ratings, the overall explanatory power of the model is quite low, as indicated by the R² value. This suggests that other unexamined factors are likely influencing user ratings. Future research could explore additional variables, such as service quality or price, to gain further insights into the factors that influence users’ ratings.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_Report_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Group_Report_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>